host: 127.0.0.1:1323
info:
  contact:
    name: API Support
  description: This is national education data dictionary backend-api server. Updated@
    2022-09-03T21:10:00+10:00
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: National Education Data Dictionary API
  version: "1.0"
paths:
  /api/entity/db:
    put:
      consumes:
      - multipart/form-data
      parameters:
      - default: dictionary
        description: database name
        in: formData
        name: database
        required: true
        type: string
      - default: entity
        description: collection name
        in: formData
        name: collection
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - set db successfully
        "400":
          description: Fail - invalid fields
      summary: set mongodb database and collection for entity storage
      tags:
      - Entity
  /api/entity/find:
    get:
      consumes:
      - application/json
      parameters:
      - description: json data for query
        format: binary
        in: body
        name: data
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - find successfully
        "400":
          description: Fail - invalid parameters or request body
        "500":
          description: Fail - internal error
      summary: find entities json content by pass a json query string via payload
      tags:
      - Entity
  /api/entity/insert/{entityName}:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity name for incoming entity data
        in: path
        name: entityName
        required: true
        type: string
      - description: entity json data for uploading
        format: binary
        in: body
        name: entityData
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - insert or update successfully
        "400":
          description: Fail - invalid parameters or request body
        "500":
          description: Fail - internal error
      summary: insert or update one entity data by a json file
      tags:
      - Entity
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
