host: 127.0.0.1:1323
info:
  contact:
    name: API Support
  description: This is national education data dictionary backend-api server. Updated@
    2022-09-15T09:29:03+10:00
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: National Education Data Dictionary API
  version: "1.0"
paths:
  /api/admin/email:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 'unique user names, separator is '','' '
        in: formData
        name: unames
        required: true
        type: string
      - description: subject for email
        in: formData
        name: subject
        required: true
        type: string
      - description: body for email
        in: formData
        name: body
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - list successfully
        "401":
          description: Fail - unauthorized error
        "403":
          description: Fail - forbidden error
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      tags:
      - Admin
  /api/admin/user/action-list/{action}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user registered unique name
        in: query
        name: uname
        required: true
        type: string
      - description: which action type [submit, approve, subscribe] record want to
          list
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - list successfully
        "401":
          description: Fail - unauthorized error
        "403":
          description: Fail - forbidden error
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: list user's action record
      tags:
      - Admin
  /api/admin/user/list/{fields}:
    get:
      consumes:
      - application/json
      parameters:
      - description: user filter with uname wildcard(*)
        in: query
        name: uname
        type: string
      - description: user filter with name wildcard(*)
        in: query
        name: name
        type: string
      - description: user filter with active status
        in: query
        name: active
        type: string
      - description: which user's fields (sep by ',') want to list. if empty, return
          all fields
        in: path
        name: fields
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - list successfully
        "401":
          description: Fail - unauthorized error
        "403":
          description: Fail - forbidden error
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: list users' info
      tags:
      - Admin
  /api/dictionary/auth/approve:
    put:
      consumes:
      - application/json
      parameters:
      - description: entity/collection 'Entity' name for approval
        in: query
        name: name
        required: true
        type: string
      - description: item type, can only be [entity collection]
        in: query
        name: kind
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - approve successfully
        "400":
          description: Fail - invalid parameters or request body
        "404":
          description: Fail - couldn't find item to approve
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: approve one dictionary candidate item
      tags:
      - Dictionary
  /api/dictionary/auth/check/{action}:
    get:
      consumes:
      - application/json
      parameters:
      - description: which action what to list its item record
        in: path
        name: action
        required: true
        type: string
      - description: entity/collection 'Entity' name for checking existing status
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - get existing status successfully
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: check recorded action item existing status from [submit, approve, subscribe]
      tags:
      - Dictionary
  /api/dictionary/auth/clear/{kind}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: item type, can only be [entity collection]
        in: path
        name: kind
        required: true
        type: string
      - description: which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - cleared successfully
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: delete all entities or collections (dangerous)
      tags:
      - Dictionary
  /api/dictionary/auth/list/{action}:
    get:
      consumes:
      - application/json
      parameters:
      - description: which action what to list its item record
        in: path
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - get list successfully
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: list recorded action items from [submit, approve, subscribe]
      tags:
      - Dictionary
  /api/dictionary/auth/one:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Entity name for deleting
        in: query
        name: name
        required: true
        type: string
      - description: from which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - deleted successfully
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: delete one entity or collection by its 'Entity' name
      tags:
      - Dictionary
  /api/dictionary/auth/subscribe:
    put:
      consumes:
      - application/json
      parameters:
      - description: entity/collection 'Entity' name for approval
        in: query
        name: name
        required: true
        type: string
      - description: item type, can only be [entity collection]
        in: query
        name: kind
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'OK - subscribe/unsubscribe successfully. true: subscribed
            now; false: unsubscribed now'
        "400":
          description: Fail - invalid parameters or request body
        "404":
          description: Fail - couldn't find item to subscribe
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: toggle subscribe one dictionary item
      tags:
      - Dictionary
  /api/dictionary/auth/upsert:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity or collection json data for uploading
        format: binary
        in: body
        name: entity
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - insert or update successfully
        "400":
          description: Fail - invalid parameters or request body
        "500":
          description: Fail - internal error
      security:
      - ApiKeyAuth: []
      summary: insert or update one entity or collection data by json payload
      tags:
      - Dictionary
  /api/dictionary/pub/colentities:
    get:
      consumes:
      - application/json
      parameters:
      - description: collection name
        in: query
        name: colname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - got collection content successfully
        "500":
          description: Fail - internal error
      summary: get related entities' name of a collection
      tags:
      - Dictionary
  /api/dictionary/pub/entclasses:
    get:
      consumes:
      - application/json
      parameters:
      - description: entity name
        in: query
        name: entname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - got entity class info successfully
        "500":
          description: Fail - internal error
      summary: get class info (derived path & children) of an entity
      tags:
      - Dictionary
  /api/dictionary/pub/exists:
    get:
      consumes:
      - application/json
      parameters:
      - description: Entity name
        in: query
        name: name
        required: true
        type: string
      - description: from which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - got successfully
        "500":
          description: Fail - internal error
      summary: check whether one item exists according to its 'Entity' name
      tags:
      - Dictionary
  /api/dictionary/pub/items/{kind}:
    get:
      consumes:
      - application/json
      parameters:
      - description: item type, can only be [entity collection]
        in: path
        name: kind
        required: true
        type: string
      - description: entity/collection 'Entity' name for query. if empty, get all
        in: query
        name: name
        type: string
      - description: from which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - get successfully
        "500":
          description: Fail - internal error
      summary: get all entities' or collections' full content
      tags:
      - Dictionary
  /api/dictionary/pub/kind:
    get:
      consumes:
      - application/json
      parameters:
      - description: Entity name for checking kind
        in: query
        name: name
        required: true
        type: string
      - description: from which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - got kind ('entity' or 'collection') successfully
        "404":
          description: Fail - neither 'entity' nor 'collection'
      summary: check item's kind ('entity' or 'collection') by its name
      tags:
      - Dictionary
  /api/dictionary/pub/list/{kind}:
    get:
      consumes:
      - application/json
      parameters:
      - description: item type, can only be [entity collection]
        in: path
        name: kind
        required: true
        type: string
      - description: entity/collection 'Entity' name for query. if empty, get all
        in: query
        name: name
        type: string
      - description: from which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - list successfully
        "500":
          description: Fail - internal error
      summary: list all entities' or collections' name
      tags:
      - Dictionary
  /api/dictionary/pub/one:
    get:
      consumes:
      - application/json
      parameters:
      - description: Entity name
        in: query
        name: name
        required: true
        type: string
      - description: regex applies?
        in: query
        name: fuzzy
        type: boolean
      - description: from which db collection? [existing, text, html]
        in: query
        name: dbcol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - got successfully
        "400":
          description: Fail - invalid parameters
        "404":
          description: Fail - not found
        "500":
          description: Fail - internal error
      summary: get one entity or collection by its 'Entity' name
      tags:
      - Dictionary
  /api/dictionary/pub/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: search content from whole dictionary
        in: query
        name: aim
        type: string
      - description: case insensitive ?
        in: query
        name: ignorecase
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK - got list of found item's name successfully
        "400":
          description: Fail - invalid parameters
        "500":
          description: Fail - internal error
      summary: get list of entity's & collection's name by searching. If not given,
        return all
      tags:
      - Dictionary
  /api/system/tag:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK - get its tag
      summary: get this api service project github version tag
      tags:
      - System
  /api/system/ver:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK - get its version
      summary: get this api service version
      tags:
      - System
  /api/user/auth/uname:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK - got uname
      security:
      - ApiKeyAuth: []
      summary: get uname
      tags:
      - User
  /api/user/pub/sign-in:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: user name or email
        in: formData
        name: uname
        required: true
        type: string
      - description: password
        format: password
        in: formData
        name: pwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - sign-in successfully
        "400":
          description: Fail - incorrect password
        "500":
          description: Fail - internal error
      summary: sign in action. if ok, got token
      tags:
      - User
  /api/user/pub/sign-out:
    put:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK - sign-out successfully
        "500":
          description: Fail - internal error
      summary: sign out action.
      tags:
      - User
  /api/user/pub/sign-up:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: unique user name
        in: formData
        name: uname
        required: true
        type: string
      - description: user's email
        format: email
        in: formData
        name: email
        required: true
        type: string
      - description: user's password
        in: formData
        name: pwd
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - then waiting for verification code
        "400":
          description: Fail - invalid registry fields
        "500":
          description: Fail - internal error
      summary: sign up action, send user's basic info for registry
      tags:
      - User
  /api/user/pub/verify-email:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: unique user name
        in: formData
        name: uname
        required: true
        type: string
      - description: verification code (in user's email)
        in: formData
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - sign-up successfully
        "400":
          description: Fail - incorrect verification code
        "500":
          description: Fail - internal error
      summary: sign up action, step 2. send back email verification code
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
