host: 127.0.0.1:1323
info:
  contact:
    name: API Support
  description: This is national education data dictionary backend-api server. Updated@
    2022-09-15T09:29:03+10:00
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: National Education Data Dictionary API
  version: "1.0"
paths:
  /api/dictionary/clear/{itemType}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: item type, only can be 'entity' or 'collection'
        in: path
        name: itemType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - cleared successfully
        "500":
          description: Fail - internal error
      summary: delete all entities or collections (dangerous)
      tags:
      - Dictionary
  /api/dictionary/items/{itemType}:
    get:
      consumes:
      - application/json
      parameters:
      - description: item type, only can be 'entity' or 'collection'
        in: path
        name: itemType
        required: true
        type: string
      - description: entity/collection 'Entity' name for query. if empty, get all
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - get successfully
        "500":
          description: Fail - internal error
      summary: get all entities' or collections' full content
      tags:
      - Dictionary
  /api/dictionary/list/{itemType}:
    get:
      consumes:
      - application/json
      parameters:
      - description: item type, only can be 'entity' or 'collection'
        in: path
        name: itemType
        required: true
        type: string
      - description: entity/collection 'Entity' name for query. if empty, get all
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - list successfully
        "500":
          description: Fail - internal error
      summary: list all entities' or collections' name
      tags:
      - Dictionary
  /api/dictionary/one:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Entity name for deleting
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - deleted successfully
        "500":
          description: Fail - internal error
      summary: delete one entity or collection by its 'Entity' name
      tags:
      - Dictionary
    get:
      consumes:
      - application/json
      parameters:
      - description: Entity name
        in: query
        name: name
        required: true
        type: string
      - description: regex applies?
        in: query
        name: fuzzy
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK - got successfully
        "400":
          description: Fail - invalid parameters
        "404":
          description: Fail - not found
        "500":
          description: Fail - internal error
      summary: get one entity or collection by its 'Entity' name
      tags:
      - Dictionary
  /api/dictionary/upsert:
    post:
      consumes:
      - application/json
      parameters:
      - description: entity or collection json data for uploading
        format: binary
        in: body
        name: entity
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK - insert or update successfully
        "400":
          description: Fail - invalid parameters or request body
        "500":
          description: Fail - internal error
      summary: insert or update one entity or collection data by json payload
      tags:
      - Dictionary
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
